version: "3.4"
volumes:
  l4d2_data:
services:
  l4d2:
    image: joshhsoj1902/docker-linuxgsm-images:latest-l4d2-8coop
    environment:
      - SERVERNAME="LGSM L4D2 Server"
      - RCON_PASSWORD="ADMINPASSWORD"
      # Setting a password currently causes LinuxGSM to fail to healthcheck the server
      # - SV_PASSWORD=""
      - LGSM_SERVER_PORT=27015
      # - LGSM_STATUS_ALERT="on"
      # - LGSM_DISCORD_ALERT="on"
      # - LGSM_DISCORD_WEBHOOK=""
      # Only need to set IP if you want a different name in the alerts.
      # - LGSM_DISPLAY_IP=""

    volumes:
      - l4d2_data:/data
    ports:
      - "27015:27015/tcp"
      - "27015:27015/udp"
    restart: always
