version: 2.1

define:
  &images [
    factorio-base,
    gmod-base,
    minecraft-paper-base,
    # project-zombiod-base,
    satisfactory-base,
    sdtd-base,
  ]

executors:
  docker-publisher:
    machine: true
    resource_class: joshhsoj1902/ubuntu
    environment:
      IMAGE_NAME: joshhsoj1902/docker-linuxgsm-images
  docker-cimg:
    machine: true
    resource_class: joshhsoj1902/ubuntu

jobs:
  build-docker:
    parameters:
      dir:
        type: string
    executor: docker-publisher
    steps:
      - checkout
      - run:
          name: "Build image"
          command: |
            docker build -f images/<< parameters.dir >>/Dockerfile -t $IMAGE_NAME:latest-<< parameters.dir >> images/<< parameters.dir >>

  test-docker:
    parameters:
      dir:
        type: string
    executor: docker-publisher
    steps:
      - checkout
      - run: mkdir -p rendered_serverconfig
      - run:
          name: "Start image"
          command: |
            HOST_IP=`hostname -I | awk '{print $1}'`
            # npm install gamedig -g
            docker compose -f images/<< parameters.dir >>/.tests/docker-compose.yml up -d

            sleep 10

            x=1
            while [ $x -le 60 ]
            do
              echo "Testing Gameserver. iteration $x"

              GAMENAME=`./images/<< parameters.dir >>/.tests/gamedig.sh $HOST_IP | jq -r .name`
              if [ "$GAMENAME" = "LinuxGSM" ];
              then
                echo "Gameserver is healthy."
                break
              else
                echo "($GAMENAME) != (LinuxGSM)"
                ./images/<< parameters.dir >>/.tests/gamedig.sh $HOST_IP
              fi

              x=$(( $x + 1 ))
              sleep 10
            done

            echo "v=========================v"
            docker compose -f images/<< parameters.dir >>/.tests/docker-compose.yml logs --tail 25
            echo "^=========================^"

            if [ $x -ge 60 ];
            then
              echo "Gameserver wasn't ready in time."
              exit 1
            fi
      - run:
          name: Run Tests
          shell: bash
          command: |
            # Run pre-install scripts
            if [ -d "images/<< parameters.dir >>/.tests/scripts" ]; then
              for f in images/<< parameters.dir >>/.tests/scripts/*.sh; do
                if ! bash "$f"
                then
                  echo "Failed running script \"$f\""
                  exit 1
                fi
              done
            fi
      - store_artifacts:
          path: rendered_serverconfig
      - run:
          name: "Cleanup"
          command: docker compose -f images/<< parameters.dir >>/.tests/docker-compose.yml down
          when: always

  publish-docker-latest:
    parameters:
      dir:
        type: string
    executor: docker-publisher
    steps:
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            IMAGE_TAG="0.0.${CIRCLE_BUILD_NUM}-<< parameters.dir >>"
            docker tag $IMAGE_NAME:latest-<< parameters.dir >> $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:latest-<< parameters.dir >>
            docker push $IMAGE_NAME:$IMAGE_TAG
  publish-docker-tag:
    parameters:
      dir:
        type: string
    executor: docker-publisher
    steps:
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            IMAGE_TAG=${CIRCLE_TAG/v/''}
            docker tag $IMAGE_NAME:latest-<< parameters.dir >> $IMAGE_NAME:$IMAGE_TAG-<< parameters.dir >>
            docker push $IMAGE_NAME:$IMAGE_TAG-<< parameters.dir >>
  # check-sdtd-config:
  #   executor: docker-cimg
  #   steps:
  #     - run: mkdir -p /tmp/serverconfig
  #     - run:
  #         name: install Gomplate
  #         command: |
  #           curl -o ~/gomplate -sSL https://github.com/hairyhenderson/gomplate/releases/download/v3.11.6/gomplate_linux-amd64-slim
  #           chmod 755 ~/gomplate
  #     - checkout
  #     - run:
  #         name: Download current LGSM serverconfig
  #         command: wget -O /tmp/serverconfig/lgsm-serverconfig.xml https://raw.githubusercontent.com/GameServerManagers/Game-Server-Configs/main/sdtd/serverconfig.xml
  #     - run:
  #         name: Render default serverconfig
  #         command: ~/gomplate -f images/sdtd-base/layers/001-base/serverfiles/sdtdserver.xml.gomplate -o /tmp/serverconfig/gomplate-serverconfig.xml
  #     - store_artifacts:
  #         path: /tmp/serverconfig
  #     - run:
  #         name: Diff two configs
  #         command:

workflows:
  build:
    jobs:
      - build-docker:
          name: build << matrix.dir >>
          matrix:
            parameters:
              dir: *images
      - test-docker:
          name: test << matrix.dir >>
          matrix:
            parameters:
              dir: *images
          requires:
            - build << matrix.dir >>
      - publish-docker-latest:
          name: publish latest << matrix.dir >>
          matrix:
            parameters:
              dir: *images
          requires:
            - test << matrix.dir >>
          filters:
            branches:
              only: main
  tag-release:
    jobs:
      - build-docker:
          name: build << matrix.dir >>
          matrix:
            parameters:
              dir: *images
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - test-docker:
          name: test << matrix.dir >>
          matrix:
            parameters:
              dir: *images
          requires:
            - build << matrix.dir >>
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish-docker-tag:
          name: publish tag << matrix.dir >>
          matrix:
            parameters:
              dir: *images
          requires:
            - test << matrix.dir >>
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
  # checks:
  #   jobs:
  #     - check-sdtd-config
