version: 2.1
executors:
  docker-game-publisher:
    machine: true
    resource_class: joshhsoj1902/ubuntu
    environment:
      IMAGE_NAME: joshhsoj1902/docker-linuxgsm-images
  docker-scripts-publisher:
    resource_class: "small"
    environment:
      IMAGE_NAME: joshhsoj1902/docker-linuxgsm-scripts
    docker:
      - image: joshhsoj1902/circleci-build-image:latest
  docker-cimg:
    machine: true
    resource_class: joshhsoj1902/ubuntu

jobs:
  ####################################
  # Shared scripts image build steps #
  ####################################

  build-docker-scripts:
    executor: docker-scripts-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build image"
          command: |
            pwd
            ls -ltr
            cd scripts
            pwd
            ls -ltr
            make build
      - run:
          name: "Test image"
          command: |
            cd scripts
            make test
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-docker-scripts-latest:
    executor: docker-scripts-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            IMAGE_TAG="0.0.${CIRCLE_BUILD_NUM}"
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_TAG
  publish-docker-scripts-tag:
    executor: docker-scripts-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build image"
          command: |
            cd scripts
            docker pull $IMAGE_NAME:latest
            make build
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            IMAGE_TAG=${CIRCLE_TAG/v/''}
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_TAG

workflows:
  ####################################
  # Shared scripts image build steps #
  ####################################

  build-scripts:
    jobs:
      - build-docker-scripts
      - publish-docker-scripts-latest:
          requires:
            - build-docker-scripts
          filters:
            branches:
              only: main
      - publish-docker-scripts-tag:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

