version: "3.4"
volumes:
  fastdl_assets:
services:
  setup_fastdl_assets:
    image: busybox
    volumes:
      - fastdl_assets:/mnt/html
    command: /bin/sh -c 'mkdir -p /mnt/html/fastdl && chown -R 1000:1000 /mnt/html'
  linuxgsm:
    image: joshhsoj1902/docker-linuxgsm-images:latest-gmod-base
    environment:
      - DOWNLOADURI="http://${NGINX_HOST:-localhost}:${NGINX_PORT:-8080}/fastdl"
      - NGINX_PORT=${NGINX_PORT:-8080}
    volumes:
      # - ${GAMEDATA_PATH:-./gamedata}:/data
      - fastdl_assets:/app/public_html
    # ports:
    #   - "27015:27015/tcp"
    #   - "27015:27015/udp"
    network_mode: host
    restart: always
  fastdl_webserver:
    image: nginx
    restart: always
    ports:
      - "${NGINX_PORT:-8080}:80"
    volumes:
      - "fastdl_assets:/usr/share/nginx/html"
    depends_on:
      - linuxgsm
