name: "Build Docker Image"
on:
  - push
  - release
jobs:
  build-docker:
    strategy:
      matrix:
        target: [
          factorio-base,
          gmod-base,
          minecraft-paper-base,
          palworld-base,
          project-zomboid-base,
          satisfactory-base,
          sdtd-base,
          sdtd-a19,
          sdtd-a21,
          # l4d2-base,
          # l4d2-8coop,
        ]
    runs-on: self-hosted

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            changed:
              - '${{ matrix.target }}/**'
              - '.github/**'
      - name: Build Skipped
        if: steps.filter.outputs.changed != 'true'
        run: echo "No Changes, Skipping build"
      - name: Build Image
        if: steps.filter.outputs.changed == 'true'
        run: IMAGE_DIR=${{ matrix.target }} ./do build
      - name: Test Image
        if: steps.filter.outputs.changed == 'true'
        shell: bash
        run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          IMAGE_DIR=${{ matrix.target }} ./do test
      - name: "Cleanup"
        if: failure()
        run: docker compose -f images/${{ matrix.target }}/.tests/docker-compose.yml down

      - name: Deploy Main
        if: ${{ (github.ref == 'refs/heads/main') && (steps.filter.outputs.changed == 'true') }}
        run: |
          IMAGE_TAG="0.0.${{ github.run_id }}-${{ matrix.target }}"
          docker tag $IMAGE_NAME:latest-${{ matrix.target }} $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:latest-${{ matrix.target }}
          docker push $IMAGE_NAME:$IMAGE_TAG
      - name: Deploy Tag
        if: ${{ (startsWith(github.ref, 'refs/tags')) && (steps.filter.outputs.changed == 'true') }}
        run: |
          IMAGE_TAG="${{ github.ref_name }}"
          docker tag $IMAGE_NAME:latest-${{ matrix.target }} $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:$IMAGE_TAG-${{ matrix.target }}
